import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
import com.github.jengelman.gradle.plugins.shadow.transformers.PreserveFirstFoundResourceTransformer

plugins {
    alias(libs.plugins.shadow) apply false
}

allprojects {
    group = "dev.imprex.orebfuscator"
    version = providers.gradleProperty("buildVersion").getOrElse("5.0.0-b0")
    description = "High-Performance Anti X-Ray"
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'java-library'

    pluginManager.withPlugin("com.gradleup.shadow") {
        tasks.withType(ShadowJar).configureEach {
            duplicatesStrategy = DuplicatesStrategy.INCLUDE
            failOnDuplicateEntries = true
            transform(PreserveFirstFoundResourceTransformer) {
                include("META-INF/LICENSE", "META-INF/io.netty.versions.properties")
            }
        }
    }

    repositories {
        mavenCentral()
        maven {
            name = 'spigot'
            url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/'
        }
        maven {
            name = 'papermc'
            url = 'https://repo.papermc.io/repository/maven-public/'
        }
        maven {
            name = 'codemc'
            url = 'https://repo.codemc.io/repository/maven-releases/'
        }
        mavenLocal()
    }

    dependencies {
        compileOnly(rootProject.libs.jspecify)
        compileOnly(rootProject.libs.annotations)

        testImplementation(platform(rootProject.libs.junit.bom))
        testImplementation(rootProject.libs.junit.jupiter)
        testRuntimeOnly(rootProject.libs.junit.platform)
    }

    java {
        toolchain.languageVersion = JavaLanguageVersion.of(17)
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    tasks.test {
        useJUnitPlatform()
    }
}
