# Done to increase the memory available to gradle.
org.gradle.parallel=true
org.gradle.daemon=true

org.gradle.configuration-cache=false
org.gradle.vfs.watch=false
org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8
org.gradle.java.installations.fromEnv=JAVA_HOME_17_X64,JAVA_HOME_21_X64,JAVA_HOME_25_X64
