dependencies {
    compileOnly(libs.paper)
    compileOnly(project(":orebfuscator-bukkit:orebfuscator-bukkit-nms"))
    compileOnly(project(":orebfuscator-bukkit:orebfuscator-bukkit-compatibility"))
    // spigot support disabled
    // compileOnly(project(":orebfuscator-bukkit:orebfuscator-bukkit-compatibility:orebfuscator-bukkit-compatibility-spigot"))
}