dependencies {
    compileOnly(project(":orebfuscator-bukkit:orebfuscator-bukkit-nms"))
    compileOnly("org.spigotmc:spigot:26.1.2-R0.1-SNAPSHOT")
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
}

tasks.withType(JavaCompile).configureEach {
    options.release = 17
}

configurations.named("compileClasspath") {
    attributes {
        attribute(TargetJvmVersion.TARGET_JVM_VERSION_ATTRIBUTE, 25)
    }
}
